Updated Readme

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -1,10 +1,24 @@
 #!/usr/bin/env bash
-# Bash script that transfers a file from our client to a server:
 
-if [ "$#" -lt 3 ]; then
-	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
-elif [ "$#" -lt 4 ]; then
-	scp -o StrictHostKeyChecking=no "$1" "$3@$2":~/
-else
-	scp -i "$4" -o StrictHostKeyChecking=no "$1" "$3@$2":~/
-fi
+#check the number of arguments
+if [ "$#" -lt 4 ]; then
+  echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+    exit 1
+    fi
+
+# Assign arguments to variables
+    PATH_TO_FILE="$1"
+    IP="$2"
+    USERNAME="$3"
+    PATH_TO_SSH_KEY="$4"
+
+# Use scp to transfer the file to the server
+    scp -o StrictHostKeyChecking=no -i "$PATH_TO_SSH_KEY" "$PATH_TO_FILE" "$USERNAME@$IP":~/
+
+# Check the exit status of the scp command
+    if [ "$?" -eq 0 ]; then
+      echo "File transferred successfully."
+      else
+        echo "File transfer failed."
+      fi
+
